name: Notify today's school lunch

on:
  schedule:
    - cron:  '30 22 * * *'   # JST 7:30に相当（UTC基準）
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Tokyo
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: python -m pip install -r requirements.txt
      - name: Run notification script
        run: python scripts/notify_menu.py
        env:
          LINE_NOTIFY_TOKEN: ${{ secrets.LINE_NOTIFY_TOKEN }}
